/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCESNLPsolver_fast_model_ ## ID
#endif

#include <math.h> 
#include "FORCESNLPsolver_fast_model.h"

#ifndef casadi_real
#define casadi_real FORCESNLPsolver_fast_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[19] = {15, 1, 0, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[19] = {1, 12, 0, 1, 2, 2, 2, 3, 4, 4, 4, 4, 4, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s4[12] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
static const casadi_int casadi_s5[41] = {8, 12, 0, 0, 1, 2, 5, 6, 7, 10, 15, 18, 21, 25, 26, 7, 2, 3, 5, 6, 0, 1, 2, 5, 6, 0, 1, 3, 5, 6, 0, 1, 4, 4, 5, 6, 0, 1, 5, 6, 7};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[25] = {4, 12, 0, 2, 2, 2, 2, 6, 10, 10, 10, 10, 10, 10, 10, 0, 1, 0, 1, 2, 3, 0, 1, 2, 3};

/* FORCESNLPsolver_fast_objective_0:(i0[12],i1[15])->(o0,o1[1x12,4nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.0000000000000003e-02;
  a1=arg[1]? arg[1][8] : 0;
  a2=sin(a1);
  a3=arg[0]? arg[0][4] : 0;
  a4=arg[1]? arg[1][6] : 0;
  a5=(a3-a4);
  a5=(a2*a5);
  a6=cos(a1);
  a7=arg[0]? arg[0][5] : 0;
  a8=arg[1]? arg[1][7] : 0;
  a9=(a7-a8);
  a9=(a6*a9);
  a5=(a5-a9);
  a9=casadi_sq(a5);
  a9=(a0*a9);
  a10=500.;
  a11=cos(a1);
  a3=(a3-a4);
  a3=(a11*a3);
  a1=sin(a1);
  a7=(a7-a8);
  a7=(a1*a7);
  a3=(a3+a7);
  a7=casadi_sq(a3);
  a7=(a10*a7);
  a9=(a9+a7);
  a7=250.;
  a8=2.5000000000000001e-02;
  a4=arg[0]? arg[0][1] : 0;
  a8=(a8*a4);
  a7=(a7*a8);
  a9=(a9-a7);
  a7=1000.;
  a8=arg[0]? arg[0][0] : 0;
  a4=(a7*a8);
  a12=100.;
  a13=casadi_sq(a8);
  a13=(a12*a13);
  a4=(a4+a13);
  a9=(a9+a4);
  if (res[0]!=0) res[0][0]=a9;
  a8=(a8+a8);
  a12=(a12*a8);
  a12=(a12+a7);
  if (res[1]!=0) res[1][0]=a12;
  a12=-6.2500000000000000e+00;
  if (res[1]!=0) res[1][1]=a12;
  a3=(a3+a3);
  a10=(a10*a3);
  a11=(a11*a10);
  a5=(a5+a5);
  a0=(a0*a5);
  a2=(a2*a0);
  a11=(a11+a2);
  if (res[1]!=0) res[1][2]=a11;
  a1=(a1*a10);
  a6=(a6*a0);
  a1=(a1-a6);
  if (res[1]!=0) res[1][3]=a1;
  return 0;
}

int FORCESNLPsolver_fast_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FORCESNLPsolver_fast_objective_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_fast_objective_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_fast_objective_0_free_mem(int mem) {
}

int FORCESNLPsolver_fast_objective_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver_fast_objective_0_release(int mem) {
}

void FORCESNLPsolver_fast_objective_0_incref(void) {
}

void FORCESNLPsolver_fast_objective_0_decref(void) {
}

casadi_int FORCESNLPsolver_fast_objective_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_fast_objective_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolver_fast_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int FORCESNLPsolver_fast_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_fast_dynamics_0:(i0[12],i1[15])->(o0[8],o1[8x12,26nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][4] : 0;
  a1=2.5000000000000001e-02;
  a2=arg[0]? arg[0][7] : 0;
  a3=arg[0]? arg[0][8] : 0;
  a4=arg[0]? arg[0][10] : 0;
  a5=(a3+a4);
  a6=cos(a5);
  a7=(a2*a6);
  a7=(a1*a7);
  a0=(a0+a7);
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][5] : 0;
  a7=(a3+a4);
  a8=sin(a7);
  a9=(a2*a8);
  a9=(a1*a9);
  a0=(a0+a9);
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][6] : 0;
  a9=arg[0]? arg[0][2] : 0;
  a9=(a1*a9);
  a9=(a0+a9);
  if (res[0]!=0) res[0][2]=a9;
  a9=arg[0]? arg[0][3] : 0;
  a10=(a1*a9);
  a10=(a2+a10);
  if (res[0]!=0) res[0][3]=a10;
  a10=arg[0]? arg[0][9] : 0;
  a11=(a1*a10);
  a3=(a3+a11);
  if (res[0]!=0) res[0][4]=a3;
  a3=3.7400000000000002e+00;
  a11=1.0488999999999999e+00;
  a12=1.5875000000000000e-01;
  a13=4.7180000000000000e+00;
  a14=1.6819245000000000e+00;
  a15=7.3999999999999996e-02;
  a16=(a15*a9);
  a16=(a14-a16);
  a16=(a13*a16);
  a17=(a12*a16);
  a18=(a17*a0);
  a19=9.3546548999999990e-01;
  a20=1.5573375000000000e+00;
  a21=(a15*a9);
  a21=(a20+a21);
  a19=(a19*a21);
  a21=7.4898250000000000e-01;
  a22=(a15*a9);
  a22=(a14-a22);
  a21=(a21*a22);
  a19=(a19-a21);
  a21=(a19*a4);
  a18=(a18+a21);
  a21=1.1890097187500000e-01;
  a22=(a15*a9);
  a22=(a14-a22);
  a21=(a21*a22);
  a22=1.6038555826049997e-01;
  a23=(a15*a9);
  a23=(a20+a23);
  a22=(a22*a23);
  a21=(a21+a22);
  a22=(a21*a10);
  a22=(a22/a2);
  a18=(a18-a22);
  a18=(a11*a18);
  a18=(a3*a18);
  a23=1.5559024000000001e-02;
  a18=(a18/a23);
  a18=(a1*a18);
  a18=(a10+a18);
  if (res[0]!=0) res[0][5]=a18;
  a18=(a16*a0);
  a23=5.4561999999999999e+00;
  a24=(a15*a9);
  a24=(a20+a24);
  a24=(a23*a24);
  a25=(a15*a9);
  a25=(a14-a25);
  a25=(a13*a25);
  a24=(a24+a25);
  a25=(a24*a4);
  a18=(a18-a25);
  a25=1.7144999999999999e-01;
  a26=(a15*a9);
  a20=(a20+a26);
  a23=(a23*a20);
  a25=(a25*a23);
  a15=(a15*a9);
  a14=(a14-a15);
  a13=(a13*a14);
  a12=(a12*a13);
  a25=(a25-a12);
  a12=(a25*a10);
  a12=(a12/a2);
  a18=(a18+a12);
  a18=(a11*a18);
  a13=3.3019999999999999e-01;
  a14=(a13*a2);
  a18=(a18/a14);
  a15=(a18-a10);
  a15=(a1*a15);
  a15=(a4+a15);
  if (res[0]!=0) res[0][6]=a15;
  a15=arg[0]? arg[0][11] : 0;
  a9=arg[0]? arg[0][1] : 0;
  a9=(a1*a9);
  a15=(a15+a9);
  if (res[0]!=0) res[0][7]=a15;
  if (res[1]!=0) res[1][0]=a1;
  if (res[1]!=0) res[1][1]=a1;
  if (res[1]!=0) res[1][2]=a1;
  a15=6.4271383603495948e+01;
  a9=-5.5424704999999998e-02;
  a9=(a9*a0);
  a23=1.2464915125999998e-01;
  a20=(a23*a4);
  a9=(a9+a20);
  a20=3.0698593925269982e-03;
  a20=(a20*a10);
  a20=(a20/a2);
  a9=(a9-a20);
  a9=(a11*a9);
  a9=(a3*a9);
  a9=(a15*a9);
  a9=(a1*a9);
  if (res[1]!=0) res[1][3]=a9;
  a9=-3.4913200000000000e-01;
  a9=(a9*a0);
  a0=5.4626799999999975e-02;
  a0=(a0*a4);
  a9=(a9-a0);
  a23=(a23*a10);
  a23=(a23/a2);
  a9=(a9+a23);
  a9=(a11*a9);
  a9=(a9/a14);
  a9=(a1*a9);
  if (res[1]!=0) res[1][4]=a9;
  a9=1.;
  if (res[1]!=0) res[1][5]=a9;
  if (res[1]!=0) res[1][6]=a9;
  if (res[1]!=0) res[1][7]=a9;
  a17=(a11*a17);
  a17=(a3*a17);
  a17=(a15*a17);
  a17=(a1*a17);
  if (res[1]!=0) res[1][8]=a17;
  a16=(a11*a16);
  a16=(a16/a14);
  a16=(a1*a16);
  if (res[1]!=0) res[1][9]=a16;
  a6=(a1*a6);
  if (res[1]!=0) res[1][10]=a6;
  a8=(a1*a8);
  if (res[1]!=0) res[1][11]=a8;
  if (res[1]!=0) res[1][12]=a9;
  a22=(a22/a2);
  a22=(a11*a22);
  a22=(a3*a22);
  a22=(a15*a22);
  a22=(a1*a22);
  if (res[1]!=0) res[1][13]=a22;
  a12=(a12/a2);
  a12=(a11*a12);
  a12=(a12/a14);
  a18=(a18/a14);
  a13=(a13*a18);
  a12=(a12+a13);
  a12=(a1*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][14]=a12;
  a5=sin(a5);
  a12=(a2*a5);
  a12=(a1*a12);
  a12=(-a12);
  if (res[1]!=0) res[1][15]=a12;
  a7=cos(a7);
  a12=(a2*a7);
  a12=(a1*a12);
  if (res[1]!=0) res[1][16]=a12;
  if (res[1]!=0) res[1][17]=a9;
  if (res[1]!=0) res[1][18]=a1;
  a21=(a21/a2);
  a21=(a11*a21);
  a21=(a3*a21);
  a21=(a15*a21);
  a21=(a1*a21);
  a21=(a9-a21);
  if (res[1]!=0) res[1][19]=a21;
  a25=(a25/a2);
  a25=(a11*a25);
  a25=(a25/a14);
  a21=-1.;
  a25=(a25+a21);
  a25=(a1*a25);
  if (res[1]!=0) res[1][20]=a25;
  a5=(a2*a5);
  a5=(a1*a5);
  a5=(-a5);
  if (res[1]!=0) res[1][21]=a5;
  a2=(a2*a7);
  a2=(a1*a2);
  if (res[1]!=0) res[1][22]=a2;
  a19=(a11*a19);
  a3=(a3*a19);
  a15=(a15*a3);
  a15=(a1*a15);
  if (res[1]!=0) res[1][23]=a15;
  a11=(a11*a24);
  a11=(a11/a14);
  a1=(a1*a11);
  a1=(a9-a1);
  if (res[1]!=0) res[1][24]=a1;
  if (res[1]!=0) res[1][25]=a9;
  return 0;
}

int FORCESNLPsolver_fast_dynamics_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FORCESNLPsolver_fast_dynamics_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_fast_dynamics_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_fast_dynamics_0_free_mem(int mem) {
}

int FORCESNLPsolver_fast_dynamics_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver_fast_dynamics_0_release(int mem) {
}

void FORCESNLPsolver_fast_dynamics_0_incref(void) {
}

void FORCESNLPsolver_fast_dynamics_0_decref(void) {
}

casadi_int FORCESNLPsolver_fast_dynamics_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_fast_dynamics_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolver_fast_dynamics_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_dynamics_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_dynamics_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_dynamics_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_dynamics_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int FORCESNLPsolver_fast_dynamics_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_fast_inequalities_0:(i0[12],i1[15])->(o0[4],o1[4x12,10nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a2=(a0*a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a5=(a3*a4);
  a2=(a2+a5);
  a5=arg[1]? arg[1][2] : 0;
  a2=(a2-a5);
  a5=arg[0]? arg[0][0] : 0;
  a2=(a2-a5);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[1]? arg[1][3] : 0;
  a6=(a0*a2);
  a7=arg[1]? arg[1][4] : 0;
  a8=(a3*a7);
  a6=(a6+a8);
  a8=arg[1]? arg[1][5] : 0;
  a6=(a6-a8);
  a6=(a6-a5);
  if (res[0]!=0) res[0][1]=a6;
  a6=(a0*a1);
  a5=(a3*a4);
  a6=(a6+a5);
  a5=arg[1]? arg[1][9] : 0;
  a6=(a6-a5);
  if (res[0]!=0) res[0][2]=a6;
  a0=(a0*a2);
  a3=(a3*a7);
  a0=(a0+a3);
  a3=arg[1]? arg[1][10] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][3]=a0;
  a0=-1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a1;
  if (res[1]!=0) res[1][3]=a2;
  if (res[1]!=0) res[1][4]=a1;
  if (res[1]!=0) res[1][5]=a2;
  if (res[1]!=0) res[1][6]=a4;
  if (res[1]!=0) res[1][7]=a7;
  if (res[1]!=0) res[1][8]=a4;
  if (res[1]!=0) res[1][9]=a7;
  return 0;
}

int FORCESNLPsolver_fast_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FORCESNLPsolver_fast_inequalities_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_fast_inequalities_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_fast_inequalities_0_free_mem(int mem) {
}

int FORCESNLPsolver_fast_inequalities_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver_fast_inequalities_0_release(int mem) {
}

void FORCESNLPsolver_fast_inequalities_0_incref(void) {
}

void FORCESNLPsolver_fast_inequalities_0_decref(void) {
}

casadi_int FORCESNLPsolver_fast_inequalities_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_fast_inequalities_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolver_fast_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    default: return 0;
  }
}

int FORCESNLPsolver_fast_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_fast_objective_1:(i0[12],i1[15])->(o0,o1[1x12,4nz]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=5.0000000000000003e-02;
  a1=arg[1]? arg[1][8] : 0;
  a2=sin(a1);
  a3=arg[0]? arg[0][4] : 0;
  a4=arg[1]? arg[1][6] : 0;
  a5=(a3-a4);
  a5=(a2*a5);
  a6=cos(a1);
  a7=arg[0]? arg[0][5] : 0;
  a8=arg[1]? arg[1][7] : 0;
  a9=(a7-a8);
  a9=(a6*a9);
  a5=(a5-a9);
  a9=casadi_sq(a5);
  a9=(a0*a9);
  a10=500.;
  a11=cos(a1);
  a3=(a3-a4);
  a3=(a11*a3);
  a1=sin(a1);
  a7=(a7-a8);
  a7=(a1*a7);
  a3=(a3+a7);
  a7=casadi_sq(a3);
  a7=(a10*a7);
  a9=(a9+a7);
  a7=250.;
  a8=2.5000000000000001e-02;
  a4=arg[0]? arg[0][1] : 0;
  a8=(a8*a4);
  a7=(a7*a8);
  a9=(a9-a7);
  a7=1000.;
  a8=arg[0]? arg[0][0] : 0;
  a4=(a7*a8);
  a12=100.;
  a13=casadi_sq(a8);
  a13=(a12*a13);
  a4=(a4+a13);
  a9=(a9+a4);
  if (res[0]!=0) res[0][0]=a9;
  a8=(a8+a8);
  a12=(a12*a8);
  a12=(a12+a7);
  if (res[1]!=0) res[1][0]=a12;
  a12=-6.2500000000000000e+00;
  if (res[1]!=0) res[1][1]=a12;
  a3=(a3+a3);
  a10=(a10*a3);
  a11=(a11*a10);
  a5=(a5+a5);
  a0=(a0*a5);
  a2=(a2*a0);
  a11=(a11+a2);
  if (res[1]!=0) res[1][2]=a11;
  a1=(a1*a10);
  a6=(a6*a0);
  a1=(a1-a6);
  if (res[1]!=0) res[1][3]=a1;
  return 0;
}

int FORCESNLPsolver_fast_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FORCESNLPsolver_fast_objective_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_fast_objective_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_fast_objective_1_free_mem(int mem) {
}

int FORCESNLPsolver_fast_objective_1_checkout(void) {
  return 0;
}

void FORCESNLPsolver_fast_objective_1_release(int mem) {
}

void FORCESNLPsolver_fast_objective_1_incref(void) {
}

void FORCESNLPsolver_fast_objective_1_decref(void) {
}

casadi_int FORCESNLPsolver_fast_objective_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_fast_objective_1_n_out(void) { return 2;}

casadi_real FORCESNLPsolver_fast_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int FORCESNLPsolver_fast_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver_fast_inequalities_1:(i0[12],i1[15])->(o0[4],o1[4x12,10nz]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a2, a3, a4, a5, a6, a7, a8;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[1]? arg[1][0] : 0;
  a2=(a0*a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a5=(a3*a4);
  a2=(a2+a5);
  a5=arg[1]? arg[1][2] : 0;
  a2=(a2-a5);
  a5=arg[0]? arg[0][0] : 0;
  a2=(a2-a5);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[1]? arg[1][3] : 0;
  a6=(a0*a2);
  a7=arg[1]? arg[1][4] : 0;
  a8=(a3*a7);
  a6=(a6+a8);
  a8=arg[1]? arg[1][5] : 0;
  a6=(a6-a8);
  a6=(a6-a5);
  if (res[0]!=0) res[0][1]=a6;
  a6=(a0*a1);
  a5=(a3*a4);
  a6=(a6+a5);
  a5=arg[1]? arg[1][9] : 0;
  a6=(a6-a5);
  if (res[0]!=0) res[0][2]=a6;
  a0=(a0*a2);
  a3=(a3*a7);
  a0=(a0+a3);
  a3=arg[1]? arg[1][10] : 0;
  a0=(a0-a3);
  if (res[0]!=0) res[0][3]=a0;
  a0=-1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a1;
  if (res[1]!=0) res[1][3]=a2;
  if (res[1]!=0) res[1][4]=a1;
  if (res[1]!=0) res[1][5]=a2;
  if (res[1]!=0) res[1][6]=a4;
  if (res[1]!=0) res[1][7]=a7;
  if (res[1]!=0) res[1][8]=a4;
  if (res[1]!=0) res[1][9]=a7;
  return 0;
}

int FORCESNLPsolver_fast_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FORCESNLPsolver_fast_inequalities_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver_fast_inequalities_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver_fast_inequalities_1_free_mem(int mem) {
}

int FORCESNLPsolver_fast_inequalities_1_checkout(void) {
  return 0;
}

void FORCESNLPsolver_fast_inequalities_1_release(int mem) {
}

void FORCESNLPsolver_fast_inequalities_1_incref(void) {
}

void FORCESNLPsolver_fast_inequalities_1_decref(void) {
}

casadi_int FORCESNLPsolver_fast_inequalities_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolver_fast_inequalities_1_n_out(void) { return 2;}

casadi_real FORCESNLPsolver_fast_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver_fast_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver_fast_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    default: return 0;
  }
}

int FORCESNLPsolver_fast_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
