mu: !!float 1.0489
C_sf: !!float 4.718
C_sr: !!float 5.4562
lf: !!float 0.15875
lr: !!float 0.17145
h: !!float 0.074
m: !!float 3.74
I: !!float 0.04712
s_min: !!float -0.4189
s_max: !!float 0.4189
sv_min: !!float -3.2
sv_max: !!float 3.2
v_switch: !!float 7.319
a_max: !!float 9.51
v_min: !!float -5.0
v_max: !!float 20.0
width: !!float 0.31
length: !!float 0.58
T_s: !!float 0.01 # this is set to be the timestep of the simulation
