% MPCC_solv_10N_no_warm_no_hard_gnone - a fast solver generated by FORCESPRO v5.1.0
%
%   OUTPUT = MPCC_solv_10N_no_warm_no_hard_gnone(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.c_1 - column vector of length 8
%       PARAMS.c_2 - column vector of length 10
%       PARAMS.c_3 - column vector of length 10
%       PARAMS.c_4 - column vector of length 10
%       PARAMS.c_5 - column vector of length 10
%       PARAMS.c_6 - column vector of length 10
%       PARAMS.c_7 - column vector of length 10
%       PARAMS.c_8 - column vector of length 10
%       PARAMS.c_9 - column vector of length 10
%       PARAMS.c_10 - column vector of length 10
%       PARAMS.c_11 - column vector of length 10
%       PARAMS.H_1 - matrix of size [14 x 14]
%       PARAMS.H_2 - matrix of size [14 x 14]
%       PARAMS.H_3 - matrix of size [14 x 14]
%       PARAMS.H_4 - matrix of size [14 x 14]
%       PARAMS.H_5 - matrix of size [14 x 14]
%       PARAMS.H_6 - matrix of size [14 x 14]
%       PARAMS.H_7 - matrix of size [14 x 14]
%       PARAMS.H_8 - matrix of size [14 x 14]
%       PARAMS.H_9 - matrix of size [14 x 14]
%       PARAMS.H_10 - matrix of size [14 x 14]
%       PARAMS.H_11 - matrix of size [14 x 14]
%       PARAMS.f_1 - column vector of length 14
%       PARAMS.f_2 - column vector of length 14
%       PARAMS.f_3 - column vector of length 14
%       PARAMS.f_4 - column vector of length 14
%       PARAMS.f_5 - column vector of length 14
%       PARAMS.f_6 - column vector of length 14
%       PARAMS.f_7 - column vector of length 14
%       PARAMS.f_8 - column vector of length 14
%       PARAMS.f_9 - column vector of length 14
%       PARAMS.f_10 - column vector of length 14
%       PARAMS.f_11 - column vector of length 14
%       PARAMS.C_1 - matrix of size [10 x 14]
%       PARAMS.C_2 - matrix of size [10 x 14]
%       PARAMS.C_3 - matrix of size [10 x 14]
%       PARAMS.C_4 - matrix of size [10 x 14]
%       PARAMS.C_5 - matrix of size [10 x 14]
%       PARAMS.C_6 - matrix of size [10 x 14]
%       PARAMS.C_7 - matrix of size [10 x 14]
%       PARAMS.C_8 - matrix of size [10 x 14]
%       PARAMS.C_9 - matrix of size [10 x 14]
%       PARAMS.C_10 - matrix of size [10 x 14]
%       PARAMS.A_2 - matrix of size [2 x 14]
%       PARAMS.A_3 - matrix of size [2 x 14]
%       PARAMS.A_4 - matrix of size [2 x 14]
%       PARAMS.A_5 - matrix of size [2 x 14]
%       PARAMS.A_6 - matrix of size [2 x 14]
%       PARAMS.A_7 - matrix of size [2 x 14]
%       PARAMS.A_8 - matrix of size [2 x 14]
%       PARAMS.A_9 - matrix of size [2 x 14]
%       PARAMS.A_10 - matrix of size [2 x 14]
%       PARAMS.A_11 - matrix of size [2 x 14]
%       PARAMS.b_2 - column vector of length 2
%       PARAMS.b_3 - column vector of length 2
%       PARAMS.b_4 - column vector of length 2
%       PARAMS.b_5 - column vector of length 2
%       PARAMS.b_6 - column vector of length 2
%       PARAMS.b_7 - column vector of length 2
%       PARAMS.b_8 - column vector of length 2
%       PARAMS.b_9 - column vector of length 2
%       PARAMS.b_10 - column vector of length 2
%       PARAMS.b_11 - column vector of length 2
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.X - column vector of size 132
%
%   [OUTPUT, EXITFLAG] = MPCC_solv_10N_no_warm_no_hard_gnone(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = MPCC_solv_10N_no_warm_no_hard_gnone(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also COPYING
