image: smile.png
resolution: 0.050000
origin: [-11.606540, -26.520793, 0.000000]
negate: 0
occupied_thresh: 0.65
free_thresh: 0.196

start_point: [0 , -1, 0]

# map paths
map_path: './configs/smile'
map_ext: '.png'


# starting pose for map
sx: 0
sy: -1
stheta: 0
