import numpy
import ctypes

name = "MPCC_solv_40N_warm_no_hard"
requires_callback = False
lib = "lib/libMPCC_solv_40N_warm_no_hard.so"
lib_static = "lib/libMPCC_solv_40N_warm_no_hard.a"
c_header = "include/MPCC_solv_40N_warm_no_hard.h"
nstages = 41

# Parameter             | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
params = \
[("c_1"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("H_1"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("f_1"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("C_1"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("A_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("b_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("z_init_00"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_01"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_02"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_03"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_04"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_05"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_06"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_07"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_08"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_09"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_10"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_11"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_12"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_13"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_14"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_15"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_16"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_17"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_18"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_19"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_20"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_21"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_22"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_23"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_24"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_25"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_26"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_27"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_28"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_29"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_30"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_31"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_32"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_33"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_34"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_35"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_36"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_37"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_38"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_39"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("z_init_40"           , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("num_of_threads"      , ""      , "solver_int32_unsigned", ctypes.c_uint  , numpy.uint32 , (  0,   1),    1)]

# Output                | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
outputs = \
[("X"                   , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),  492)]

# Info Struct Fields
info = \
[('it', ctypes.c_int32),
('it2opt', ctypes.c_int32),
('res_eq', ctypes.c_double),
('res_ineq', ctypes.c_double),
('pobj', ctypes.c_double),
('dobj', ctypes.c_double),
('dgap', ctypes.c_double),
('rdgap', ctypes.c_double),
('gradient_lag_norm', ctypes.c_double),
('mu', ctypes.c_double),
('mu_aff', ctypes.c_double),
('sigma', ctypes.c_double),
('lsit_aff', ctypes.c_int32),
('lsit_cc', ctypes.c_int32),
('step_aff', ctypes.c_double),
('step_cc', ctypes.c_double),
('solvetime', ctypes.c_double)
]

# Dynamics dimensions
#   nvar    |   neq   |   dimh    |   dimp    |   diml    |   dimu    |   dimhl   |   dimhu    
dynamics_dims = [
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0), 
	(14, 10, 0, 0, 12, 11, 0, 0)
]