% MPCC_solv_40N_no_warm_no_hard - a fast solver generated by FORCESPRO v5.0.1
%
%   OUTPUT = MPCC_solv_40N_no_warm_no_hard(PARAMS) solves a multistage problem
%   subject to the parameters supplied in the following struct:
%       PARAMS.c_1 - column vector of length 10
%       PARAMS.c_2 - column vector of length 10
%       PARAMS.c_3 - column vector of length 10
%       PARAMS.c_4 - column vector of length 10
%       PARAMS.c_5 - column vector of length 10
%       PARAMS.c_6 - column vector of length 10
%       PARAMS.c_7 - column vector of length 10
%       PARAMS.c_8 - column vector of length 10
%       PARAMS.c_9 - column vector of length 10
%       PARAMS.c_10 - column vector of length 10
%       PARAMS.c_11 - column vector of length 10
%       PARAMS.c_12 - column vector of length 10
%       PARAMS.c_13 - column vector of length 10
%       PARAMS.c_14 - column vector of length 10
%       PARAMS.c_15 - column vector of length 10
%       PARAMS.c_16 - column vector of length 10
%       PARAMS.c_17 - column vector of length 10
%       PARAMS.c_18 - column vector of length 10
%       PARAMS.c_19 - column vector of length 10
%       PARAMS.c_20 - column vector of length 10
%       PARAMS.c_21 - column vector of length 10
%       PARAMS.c_22 - column vector of length 10
%       PARAMS.c_23 - column vector of length 10
%       PARAMS.c_24 - column vector of length 10
%       PARAMS.c_25 - column vector of length 10
%       PARAMS.c_26 - column vector of length 10
%       PARAMS.c_27 - column vector of length 10
%       PARAMS.c_28 - column vector of length 10
%       PARAMS.c_29 - column vector of length 10
%       PARAMS.c_30 - column vector of length 10
%       PARAMS.c_31 - column vector of length 10
%       PARAMS.c_32 - column vector of length 10
%       PARAMS.c_33 - column vector of length 10
%       PARAMS.c_34 - column vector of length 10
%       PARAMS.c_35 - column vector of length 10
%       PARAMS.c_36 - column vector of length 10
%       PARAMS.c_37 - column vector of length 10
%       PARAMS.c_38 - column vector of length 10
%       PARAMS.c_39 - column vector of length 10
%       PARAMS.c_40 - column vector of length 10
%       PARAMS.c_41 - column vector of length 10
%       PARAMS.H_1 - matrix of size [14 x 14]
%       PARAMS.H_2 - matrix of size [14 x 14]
%       PARAMS.H_3 - matrix of size [14 x 14]
%       PARAMS.H_4 - matrix of size [14 x 14]
%       PARAMS.H_5 - matrix of size [14 x 14]
%       PARAMS.H_6 - matrix of size [14 x 14]
%       PARAMS.H_7 - matrix of size [14 x 14]
%       PARAMS.H_8 - matrix of size [14 x 14]
%       PARAMS.H_9 - matrix of size [14 x 14]
%       PARAMS.H_10 - matrix of size [14 x 14]
%       PARAMS.H_11 - matrix of size [14 x 14]
%       PARAMS.H_12 - matrix of size [14 x 14]
%       PARAMS.H_13 - matrix of size [14 x 14]
%       PARAMS.H_14 - matrix of size [14 x 14]
%       PARAMS.H_15 - matrix of size [14 x 14]
%       PARAMS.H_16 - matrix of size [14 x 14]
%       PARAMS.H_17 - matrix of size [14 x 14]
%       PARAMS.H_18 - matrix of size [14 x 14]
%       PARAMS.H_19 - matrix of size [14 x 14]
%       PARAMS.H_20 - matrix of size [14 x 14]
%       PARAMS.H_21 - matrix of size [14 x 14]
%       PARAMS.H_22 - matrix of size [14 x 14]
%       PARAMS.H_23 - matrix of size [14 x 14]
%       PARAMS.H_24 - matrix of size [14 x 14]
%       PARAMS.H_25 - matrix of size [14 x 14]
%       PARAMS.H_26 - matrix of size [14 x 14]
%       PARAMS.H_27 - matrix of size [14 x 14]
%       PARAMS.H_28 - matrix of size [14 x 14]
%       PARAMS.H_29 - matrix of size [14 x 14]
%       PARAMS.H_30 - matrix of size [14 x 14]
%       PARAMS.H_31 - matrix of size [14 x 14]
%       PARAMS.H_32 - matrix of size [14 x 14]
%       PARAMS.H_33 - matrix of size [14 x 14]
%       PARAMS.H_34 - matrix of size [14 x 14]
%       PARAMS.H_35 - matrix of size [14 x 14]
%       PARAMS.H_36 - matrix of size [14 x 14]
%       PARAMS.H_37 - matrix of size [14 x 14]
%       PARAMS.H_38 - matrix of size [14 x 14]
%       PARAMS.H_39 - matrix of size [14 x 14]
%       PARAMS.H_40 - matrix of size [14 x 14]
%       PARAMS.H_41 - matrix of size [14 x 14]
%       PARAMS.f_1 - column vector of length 14
%       PARAMS.f_2 - column vector of length 14
%       PARAMS.f_3 - column vector of length 14
%       PARAMS.f_4 - column vector of length 14
%       PARAMS.f_5 - column vector of length 14
%       PARAMS.f_6 - column vector of length 14
%       PARAMS.f_7 - column vector of length 14
%       PARAMS.f_8 - column vector of length 14
%       PARAMS.f_9 - column vector of length 14
%       PARAMS.f_10 - column vector of length 14
%       PARAMS.f_11 - column vector of length 14
%       PARAMS.f_12 - column vector of length 14
%       PARAMS.f_13 - column vector of length 14
%       PARAMS.f_14 - column vector of length 14
%       PARAMS.f_15 - column vector of length 14
%       PARAMS.f_16 - column vector of length 14
%       PARAMS.f_17 - column vector of length 14
%       PARAMS.f_18 - column vector of length 14
%       PARAMS.f_19 - column vector of length 14
%       PARAMS.f_20 - column vector of length 14
%       PARAMS.f_21 - column vector of length 14
%       PARAMS.f_22 - column vector of length 14
%       PARAMS.f_23 - column vector of length 14
%       PARAMS.f_24 - column vector of length 14
%       PARAMS.f_25 - column vector of length 14
%       PARAMS.f_26 - column vector of length 14
%       PARAMS.f_27 - column vector of length 14
%       PARAMS.f_28 - column vector of length 14
%       PARAMS.f_29 - column vector of length 14
%       PARAMS.f_30 - column vector of length 14
%       PARAMS.f_31 - column vector of length 14
%       PARAMS.f_32 - column vector of length 14
%       PARAMS.f_33 - column vector of length 14
%       PARAMS.f_34 - column vector of length 14
%       PARAMS.f_35 - column vector of length 14
%       PARAMS.f_36 - column vector of length 14
%       PARAMS.f_37 - column vector of length 14
%       PARAMS.f_38 - column vector of length 14
%       PARAMS.f_39 - column vector of length 14
%       PARAMS.f_40 - column vector of length 14
%       PARAMS.f_41 - column vector of length 14
%       PARAMS.C_1 - matrix of size [10 x 14]
%       PARAMS.C_2 - matrix of size [10 x 14]
%       PARAMS.C_3 - matrix of size [10 x 14]
%       PARAMS.C_4 - matrix of size [10 x 14]
%       PARAMS.C_5 - matrix of size [10 x 14]
%       PARAMS.C_6 - matrix of size [10 x 14]
%       PARAMS.C_7 - matrix of size [10 x 14]
%       PARAMS.C_8 - matrix of size [10 x 14]
%       PARAMS.C_9 - matrix of size [10 x 14]
%       PARAMS.C_10 - matrix of size [10 x 14]
%       PARAMS.C_11 - matrix of size [10 x 14]
%       PARAMS.C_12 - matrix of size [10 x 14]
%       PARAMS.C_13 - matrix of size [10 x 14]
%       PARAMS.C_14 - matrix of size [10 x 14]
%       PARAMS.C_15 - matrix of size [10 x 14]
%       PARAMS.C_16 - matrix of size [10 x 14]
%       PARAMS.C_17 - matrix of size [10 x 14]
%       PARAMS.C_18 - matrix of size [10 x 14]
%       PARAMS.C_19 - matrix of size [10 x 14]
%       PARAMS.C_20 - matrix of size [10 x 14]
%       PARAMS.C_21 - matrix of size [10 x 14]
%       PARAMS.C_22 - matrix of size [10 x 14]
%       PARAMS.C_23 - matrix of size [10 x 14]
%       PARAMS.C_24 - matrix of size [10 x 14]
%       PARAMS.C_25 - matrix of size [10 x 14]
%       PARAMS.C_26 - matrix of size [10 x 14]
%       PARAMS.C_27 - matrix of size [10 x 14]
%       PARAMS.C_28 - matrix of size [10 x 14]
%       PARAMS.C_29 - matrix of size [10 x 14]
%       PARAMS.C_30 - matrix of size [10 x 14]
%       PARAMS.C_31 - matrix of size [10 x 14]
%       PARAMS.C_32 - matrix of size [10 x 14]
%       PARAMS.C_33 - matrix of size [10 x 14]
%       PARAMS.C_34 - matrix of size [10 x 14]
%       PARAMS.C_35 - matrix of size [10 x 14]
%       PARAMS.C_36 - matrix of size [10 x 14]
%       PARAMS.C_37 - matrix of size [10 x 14]
%       PARAMS.C_38 - matrix of size [10 x 14]
%       PARAMS.C_39 - matrix of size [10 x 14]
%       PARAMS.C_40 - matrix of size [10 x 14]
%       PARAMS.A_2 - matrix of size [2 x 14]
%       PARAMS.A_3 - matrix of size [2 x 14]
%       PARAMS.A_4 - matrix of size [2 x 14]
%       PARAMS.A_5 - matrix of size [2 x 14]
%       PARAMS.A_6 - matrix of size [2 x 14]
%       PARAMS.A_7 - matrix of size [2 x 14]
%       PARAMS.A_8 - matrix of size [2 x 14]
%       PARAMS.A_9 - matrix of size [2 x 14]
%       PARAMS.A_10 - matrix of size [2 x 14]
%       PARAMS.A_11 - matrix of size [2 x 14]
%       PARAMS.A_12 - matrix of size [2 x 14]
%       PARAMS.A_13 - matrix of size [2 x 14]
%       PARAMS.A_14 - matrix of size [2 x 14]
%       PARAMS.A_15 - matrix of size [2 x 14]
%       PARAMS.A_16 - matrix of size [2 x 14]
%       PARAMS.A_17 - matrix of size [2 x 14]
%       PARAMS.A_18 - matrix of size [2 x 14]
%       PARAMS.A_19 - matrix of size [2 x 14]
%       PARAMS.A_20 - matrix of size [2 x 14]
%       PARAMS.A_21 - matrix of size [2 x 14]
%       PARAMS.A_22 - matrix of size [2 x 14]
%       PARAMS.A_23 - matrix of size [2 x 14]
%       PARAMS.A_24 - matrix of size [2 x 14]
%       PARAMS.A_25 - matrix of size [2 x 14]
%       PARAMS.A_26 - matrix of size [2 x 14]
%       PARAMS.A_27 - matrix of size [2 x 14]
%       PARAMS.A_28 - matrix of size [2 x 14]
%       PARAMS.A_29 - matrix of size [2 x 14]
%       PARAMS.A_30 - matrix of size [2 x 14]
%       PARAMS.A_31 - matrix of size [2 x 14]
%       PARAMS.A_32 - matrix of size [2 x 14]
%       PARAMS.A_33 - matrix of size [2 x 14]
%       PARAMS.A_34 - matrix of size [2 x 14]
%       PARAMS.A_35 - matrix of size [2 x 14]
%       PARAMS.A_36 - matrix of size [2 x 14]
%       PARAMS.A_37 - matrix of size [2 x 14]
%       PARAMS.A_38 - matrix of size [2 x 14]
%       PARAMS.A_39 - matrix of size [2 x 14]
%       PARAMS.A_40 - matrix of size [2 x 14]
%       PARAMS.A_41 - matrix of size [2 x 14]
%       PARAMS.b_2 - column vector of length 2
%       PARAMS.b_3 - column vector of length 2
%       PARAMS.b_4 - column vector of length 2
%       PARAMS.b_5 - column vector of length 2
%       PARAMS.b_6 - column vector of length 2
%       PARAMS.b_7 - column vector of length 2
%       PARAMS.b_8 - column vector of length 2
%       PARAMS.b_9 - column vector of length 2
%       PARAMS.b_10 - column vector of length 2
%       PARAMS.b_11 - column vector of length 2
%       PARAMS.b_12 - column vector of length 2
%       PARAMS.b_13 - column vector of length 2
%       PARAMS.b_14 - column vector of length 2
%       PARAMS.b_15 - column vector of length 2
%       PARAMS.b_16 - column vector of length 2
%       PARAMS.b_17 - column vector of length 2
%       PARAMS.b_18 - column vector of length 2
%       PARAMS.b_19 - column vector of length 2
%       PARAMS.b_20 - column vector of length 2
%       PARAMS.b_21 - column vector of length 2
%       PARAMS.b_22 - column vector of length 2
%       PARAMS.b_23 - column vector of length 2
%       PARAMS.b_24 - column vector of length 2
%       PARAMS.b_25 - column vector of length 2
%       PARAMS.b_26 - column vector of length 2
%       PARAMS.b_27 - column vector of length 2
%       PARAMS.b_28 - column vector of length 2
%       PARAMS.b_29 - column vector of length 2
%       PARAMS.b_30 - column vector of length 2
%       PARAMS.b_31 - column vector of length 2
%       PARAMS.b_32 - column vector of length 2
%       PARAMS.b_33 - column vector of length 2
%       PARAMS.b_34 - column vector of length 2
%       PARAMS.b_35 - column vector of length 2
%       PARAMS.b_36 - column vector of length 2
%       PARAMS.b_37 - column vector of length 2
%       PARAMS.b_38 - column vector of length 2
%       PARAMS.b_39 - column vector of length 2
%       PARAMS.b_40 - column vector of length 2
%       PARAMS.b_41 - column vector of length 2
%       PARAMS.num_of_threads - scalar
%
%   OUTPUT returns the values of the last iteration of the solver where
%       OUTPUT.X - column vector of size 492
%
%   [OUTPUT, EXITFLAG] = MPCC_solv_40N_no_warm_no_hard(PARAMS) returns additionally
%   the integer EXITFLAG indicating the state of the solution with 
%       1 - OPTIMAL solution has been found (subject to desired accuracy)
%       0 - Timeout - maximum number of iterations reached
%      -7 - Method could not progress. Problem may be infeasible. Run FORCESdiagnostics on your problem to check for most common errors in the formulation.
%    -100 - License error
%
%   [OUTPUT, EXITFLAG, INFO] = MPCC_solv_40N_no_warm_no_hard(PARAMS) returns 
%   additional information about the last iterate:
%       INFO.it        - number of iterations that lead to this result
%       INFO.res_eq    - max. equality constraint residual
%       INFO.res_ineq  - max. inequality constraint residual
%       INFO.pobj      - primal objective
%       INFO.dobj      - dual objective
%       INFO.dgap      - duality gap := pobj - dobj
%       INFO.rdgap     - relative duality gap := |dgap / pobj|
%       INFO.mu        - duality measure
%       INFO.sigma     - centering parameter
%       INFO.lsit_aff  - iterations of affine line search
%       INFO.lsit_cc   - iterations of line search (combined direction)
%       INFO.step_aff  - step size (affine direction)
%       INFO.step_cc   - step size (centering direction)
%       INFO.solvetime - Time needed for solve (wall clock time)
%
% See also COPYING
