mu: !!float 1
C_sf: !!float 5.438
C_sr: !!float 7.650
lf: !!float 0.151
lr: !!float 0.174
h: !!float 0.03
m: !!float 3.586
I: !!float 0.0627
s_min: !!float -0.4189
s_max: !!float 0.4189
sv_min: !!float -1.6
sv_max: !!float 1.6
v_switch: !!float 7.319
a_max: !!float 5
v_min: !!float -3.0
v_max: !!float 3.0
width: !!float 0.31
length: !!float 0.58
lower_lookahead: !!float 0.5
upper_lookahead: !!float 3.9
