# NOTE: these topic names are MOVED and not used here, check docker-compose.yml from f1tenth_docker_agent to change the ego_id and opp_id to your liking

# ego_scan_topic: '/ego_id/scan'
# opp_scan_topic: '/opp_id/scan'
# ego_odom_topic: '/ego_id/odom'
# ego_opp_odom_topic: '/ego_id/opp_odom'
# opp_odom_topic: '/opp_id/odom'
# opp_ego_odom_topic: '/opp_id/opp_odom'
# ego_drive_topic: '/ego_id/drive'
# opp_drive_topic: '/opp_id/drive'
# map_path: '/f1tenth_gym/maps/berlin.yaml'
# map_img_ext: '.png'
# executable_dir: '/f1tenth_gym/build/'

# fixed topic names DO NOT CHANGE
lap_count_topic: '/lap_count'
lap_time_topic: '/lap_time'
collision_topic: '/collision'
race_info_topic: '/race_info'

# fixed vals DO NOT CHANGE
scan_fov: 4.7
scan_beams: 1080
scan_distance_to_base_link: 0.275