import argparse

def init_parser():
    parser = argparse.ArgumentParser(description="Runs the RL train for TC-Driver")
    parser.add_argument(
        "-l",
        "--ep_len",
        type=int,
        default=500,
        help="Maximum episode length",
    )
    parser.add_argument(
        "-d",
        "--ang_deg",
        type=int,
        default=30,
        help="Limit slip angle",
    )
    parser.add_argument(
        "-v",
        "--max_vel",
        type=int,
        default=20,
        help="Maximum velocity",
    )
    parser.add_argument(
        "--display",
        dest="display",
        action="store_true",
        help="Activate video displaying",
    )
    parser.add_argument(
        "--no-display",
        dest="display",
        action="store_false",
        help="Deactivate video displaying",
    )
    parser.set_defaults(display=True)
    parser.add_argument(
        "--p_noise",
        dest="p_noise",
        action="store_true",
        help="Activate noise on dynamics parameters",
    )
    parser.add_argument(
        "--no-p_noise",
        dest="p_noise",
        action="store_false",
        help="Deactivate noise on dynamics parameters",
    )
    parser.set_defaults(p_noise=True)
    parser.add_argument(
        "--use_traj",
        dest="use_traj",
        action="store_true",
        help="Use the trajectory generated by MPC.",
    )
    parser.add_argument(
        "--no-use_traj",
        dest="use_traj",
        action="store_false",
        help="Use the center-line trajectory.",
    )
    parser.set_defaults(use_traj=True)
    
    return parser
