import numpy
import ctypes

name = "MPCC_solv_80N_no_warm_no_hard_invitedguest"
requires_callback = False
lib = "lib/libMPCC_solv_80N_no_warm_no_hard_invitedguest.so"
lib_static = "lib/libMPCC_solv_80N_no_warm_no_hard_invitedguest.a"
c_header = "include/MPCC_solv_80N_no_warm_no_hard_invitedguest.h"
nstages = 81

# Parameter             | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
params = \
[("c_1"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  8,   1),    8),
 ("c_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_42"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_43"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_44"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_45"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_46"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_47"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_48"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_49"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_50"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_51"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_52"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_53"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_54"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_55"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_56"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_57"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_58"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_59"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_60"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_61"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_62"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_63"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_64"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_65"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_66"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_67"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_68"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_69"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_70"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_71"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_72"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_73"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_74"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_75"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_76"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_77"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_78"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_79"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_80"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("c_81"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,   1),   10),
 ("H_1"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_42"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_43"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_44"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_45"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_46"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_47"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_48"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_49"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_50"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_51"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_52"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_53"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_54"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_55"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_56"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_57"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_58"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_59"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_60"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_61"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_62"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_63"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_64"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_65"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_66"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_67"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_68"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_69"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_70"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_71"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_72"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_73"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_74"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_75"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_76"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_77"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_78"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_79"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_80"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("H_81"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,  14),  196),
 ("f_1"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_42"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_43"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_44"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_45"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_46"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_47"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_48"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_49"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_50"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_51"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_52"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_53"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_54"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_55"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_56"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_57"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_58"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_59"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_60"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_61"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_62"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_63"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_64"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_65"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_66"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_67"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_68"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_69"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_70"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_71"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_72"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_73"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_74"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_75"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_76"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_77"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_78"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_79"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_80"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("f_81"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 14,   1),   14),
 ("C_1"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_42"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_43"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_44"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_45"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_46"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_47"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_48"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_49"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_50"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_51"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_52"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_53"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_54"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_55"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_56"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_57"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_58"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_59"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_60"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_61"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_62"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_63"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_64"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_65"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_66"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_67"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_68"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_69"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_70"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_71"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_72"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_73"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_74"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_75"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_76"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_77"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_78"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_79"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("C_80"                , "dense" , ""               , ctypes.c_double, numpy.float64, ( 10,  14),  140),
 ("A_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_42"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_43"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_44"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_45"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_46"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_47"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_48"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_49"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_50"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_51"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_52"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_53"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_54"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_55"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_56"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_57"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_58"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_59"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_60"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_61"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_62"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_63"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_64"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_65"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_66"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_67"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_68"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_69"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_70"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_71"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_72"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_73"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_74"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_75"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_76"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_77"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_78"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_79"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_80"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("A_81"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,  14),   28),
 ("b_2"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_3"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_4"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_5"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_6"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_7"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_8"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_9"                 , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_10"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_11"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_12"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_13"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_14"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_15"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_16"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_17"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_18"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_19"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_20"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_21"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_22"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_23"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_24"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_25"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_26"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_27"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_28"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_29"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_30"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_31"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_32"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_33"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_34"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_35"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_36"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_37"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_38"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_39"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_40"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_41"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_42"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_43"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_44"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_45"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_46"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_47"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_48"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_49"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_50"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_51"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_52"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_53"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_54"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_55"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_56"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_57"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_58"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_59"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_60"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_61"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_62"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_63"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_64"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_65"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_66"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_67"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_68"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_69"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_70"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_71"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_72"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_73"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_74"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_75"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_76"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_77"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_78"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_79"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_80"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2),
 ("b_81"                , "dense" , ""               , ctypes.c_double, numpy.float64, (  2,   1),    2)]

# Output                | Type    | Scalar type      | Ctypes type    | Numpy type   | Shape     | Len
outputs = \
[("X"                   , ""      , ""               , ctypes.c_double, numpy.float64,     ( 12,),  972)]

# Info Struct Fields
info = \
[('it', ctypes.c_int32),
('it2opt', ctypes.c_int32),
('res_eq', ctypes.c_double),
('res_ineq', ctypes.c_double),
('pobj', ctypes.c_double),
('dobj', ctypes.c_double),
('dgap', ctypes.c_double),
('rdgap', ctypes.c_double),
('gradient_lag_norm', ctypes.c_double),
('mu', ctypes.c_double),
('mu_aff', ctypes.c_double),
('sigma', ctypes.c_double),
('lsit_aff', ctypes.c_int32),
('lsit_cc', ctypes.c_int32),
('step_aff', ctypes.c_double),
('step_cc', ctypes.c_double),
('solvetime', ctypes.c_double)
]

# Dynamics dimensions
#   nvar    |   neq   |   dimh    |   dimp    |   diml    |   dimu    |   dimhl   |   dimhu    
dynamics_dims = [
	(14, 8, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0), 
	(14, 10, 0, 0, 12, 12, 0, 0)
]