/*
MPCC_solv_80N_no_warm_no_hard_invitedguest : A fast customized optimization solver.

Copyright (C) 2013-2021 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v5.1.0 on Wednesday, March 23, 2022 at 9:06:43 AM */
#ifndef MPCC_solv_80N_no_warm_no_hard_invitedguest_H
#define MPCC_solv_80N_no_warm_no_hard_invitedguest_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double MPCC_solv_80N_no_warm_no_hard_invitedguest_float;


typedef double MPCC_solv_80N_no_warm_no_hard_invitedguestinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_MPCC_solv_80N_no_warm_no_hard_invitedguest
#define MISRA_C_MPCC_solv_80N_no_warm_no_hard_invitedguest (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_MPCC_solv_80N_no_warm_no_hard_invitedguest
#define RESTRICT_CODE_MPCC_solv_80N_no_warm_no_hard_invitedguest (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_MPCC_solv_80N_no_warm_no_hard_invitedguest
#define SET_PRINTLEVEL_MPCC_solv_80N_no_warm_no_hard_invitedguest    (2)
#endif

/* timing */
#ifndef SET_TIMING_MPCC_solv_80N_no_warm_no_hard_invitedguest
#define SET_TIMING_MPCC_solv_80N_no_warm_no_hard_invitedguest    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_MPCC_solv_80N_no_warm_no_hard_invitedguest         (200)	

/* scaling factor of line search (affine direction) */
#define SET_LS_SCALE_AFF_MPCC_solv_80N_no_warm_no_hard_invitedguest  (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(0.9)      

/* scaling factor of line search (combined direction) */
#define SET_LS_SCALE_MPCC_solv_80N_no_warm_no_hard_invitedguest      (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(0.95)  

/* minimum required step size in each iteration */
#define SET_LS_MINSTEP_MPCC_solv_80N_no_warm_no_hard_invitedguest    (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(1E-08)

/* maximum step size (combined direction) */
#define SET_LS_MAXSTEP_MPCC_solv_80N_no_warm_no_hard_invitedguest    (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(0.995)

/* desired relative duality gap */
#define SET_ACC_RDGAP_MPCC_solv_80N_no_warm_no_hard_invitedguest     (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(0.01)

/* desired maximum residual on equality constraints */
#define SET_ACC_RESEQ_MPCC_solv_80N_no_warm_no_hard_invitedguest     (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(0.0001)

/* desired maximum residual on inequality constraints */
#define SET_ACC_RESINEQ_MPCC_solv_80N_no_warm_no_hard_invitedguest   (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(0.0001)

/* desired maximum violation of complementarity */
#define SET_ACC_KKTCOMPL_MPCC_solv_80N_no_warm_no_hard_invitedguest  (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(0.0001)

/* desired maximum violation of stationarity (only checked if value is > 0) */
#define SET_ACC_KKTSTAT_MPCC_solv_80N_no_warm_no_hard_invitedguest  (MPCC_solv_80N_no_warm_no_hard_invitedguest_float)(-1)

/* RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_MPCC_solv_80N_no_warm_no_hard_invitedguest      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_MPCC_solv_80N_no_warm_no_hard_invitedguest (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_MPCC_solv_80N_no_warm_no_hard_invitedguest   (2)

/* no progress in line search possible */
#define NOPROGRESS_MPCC_solv_80N_no_warm_no_hard_invitedguest   (-7)

/* fatal internal error - nans occurring */
#define NAN_MPCC_solv_80N_no_warm_no_hard_invitedguest  (-10)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_MPCC_solv_80N_no_warm_no_hard_invitedguest   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_MPCC_solv_80N_no_warm_no_hard_invitedguest   (-12)

/* thread error */
#define THREAD_FAILURE_MPCC_solv_80N_no_warm_no_hard_invitedguest  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_MPCC_solv_80N_no_warm_no_hard_invitedguest  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_MPCC_solv_80N_no_warm_no_hard_invitedguest  (-100)



/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct MPCC_solv_80N_no_warm_no_hard_invitedguest_params
{
    /* vector of size 8 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_1[8];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_2[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_3[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_4[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_5[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_6[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_7[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_8[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_9[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_10[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_11[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_12[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_13[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_14[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_15[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_16[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_17[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_18[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_19[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_20[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_21[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_22[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_23[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_24[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_25[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_26[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_27[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_28[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_29[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_30[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_31[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_32[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_33[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_34[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_35[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_36[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_37[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_38[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_39[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_40[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_41[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_42[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_43[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_44[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_45[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_46[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_47[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_48[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_49[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_50[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_51[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_52[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_53[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_54[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_55[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_56[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_57[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_58[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_59[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_60[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_61[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_62[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_63[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_64[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_65[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_66[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_67[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_68[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_69[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_70[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_71[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_72[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_73[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_74[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_75[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_76[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_77[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_78[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_79[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_80[10];

    /* vector of size 10 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float c_81[10];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_1[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_2[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_3[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_4[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_5[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_6[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_7[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_8[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_9[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_10[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_11[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_12[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_13[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_14[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_15[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_16[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_17[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_18[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_19[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_20[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_21[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_22[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_23[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_24[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_25[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_26[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_27[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_28[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_29[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_30[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_31[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_32[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_33[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_34[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_35[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_36[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_37[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_38[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_39[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_40[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_41[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_42[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_43[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_44[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_45[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_46[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_47[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_48[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_49[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_50[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_51[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_52[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_53[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_54[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_55[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_56[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_57[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_58[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_59[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_60[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_61[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_62[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_63[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_64[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_65[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_66[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_67[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_68[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_69[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_70[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_71[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_72[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_73[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_74[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_75[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_76[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_77[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_78[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_79[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_80[196];

    /* matrix of size [14 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float H_81[196];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_1[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_2[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_3[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_4[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_5[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_6[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_7[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_8[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_9[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_10[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_11[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_12[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_13[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_14[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_15[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_16[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_17[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_18[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_19[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_20[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_21[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_22[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_23[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_24[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_25[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_26[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_27[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_28[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_29[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_30[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_31[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_32[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_33[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_34[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_35[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_36[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_37[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_38[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_39[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_40[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_41[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_42[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_43[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_44[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_45[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_46[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_47[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_48[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_49[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_50[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_51[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_52[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_53[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_54[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_55[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_56[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_57[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_58[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_59[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_60[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_61[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_62[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_63[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_64[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_65[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_66[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_67[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_68[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_69[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_70[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_71[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_72[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_73[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_74[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_75[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_76[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_77[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_78[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_79[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_80[14];

    /* vector of size 14 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float f_81[14];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_1[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_2[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_3[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_4[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_5[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_6[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_7[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_8[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_9[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_10[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_11[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_12[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_13[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_14[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_15[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_16[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_17[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_18[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_19[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_20[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_21[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_22[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_23[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_24[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_25[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_26[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_27[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_28[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_29[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_30[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_31[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_32[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_33[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_34[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_35[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_36[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_37[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_38[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_39[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_40[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_41[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_42[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_43[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_44[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_45[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_46[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_47[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_48[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_49[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_50[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_51[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_52[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_53[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_54[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_55[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_56[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_57[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_58[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_59[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_60[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_61[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_62[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_63[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_64[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_65[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_66[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_67[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_68[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_69[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_70[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_71[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_72[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_73[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_74[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_75[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_76[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_77[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_78[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_79[140];

    /* matrix of size [10 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float C_80[140];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_2[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_3[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_4[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_5[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_6[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_7[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_8[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_9[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_10[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_11[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_12[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_13[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_14[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_15[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_16[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_17[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_18[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_19[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_20[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_21[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_22[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_23[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_24[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_25[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_26[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_27[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_28[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_29[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_30[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_31[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_32[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_33[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_34[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_35[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_36[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_37[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_38[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_39[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_40[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_41[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_42[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_43[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_44[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_45[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_46[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_47[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_48[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_49[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_50[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_51[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_52[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_53[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_54[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_55[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_56[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_57[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_58[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_59[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_60[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_61[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_62[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_63[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_64[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_65[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_66[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_67[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_68[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_69[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_70[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_71[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_72[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_73[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_74[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_75[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_76[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_77[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_78[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_79[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_80[28];

    /* matrix of size [2 x 14] (column major format) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float A_81[28];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_2[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_3[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_4[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_5[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_6[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_7[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_8[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_9[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_10[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_11[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_12[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_13[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_14[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_15[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_16[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_17[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_18[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_19[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_20[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_21[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_22[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_23[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_24[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_25[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_26[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_27[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_28[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_29[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_30[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_31[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_32[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_33[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_34[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_35[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_36[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_37[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_38[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_39[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_40[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_41[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_42[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_43[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_44[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_45[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_46[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_47[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_48[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_49[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_50[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_51[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_52[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_53[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_54[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_55[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_56[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_57[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_58[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_59[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_60[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_61[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_62[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_63[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_64[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_65[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_66[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_67[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_68[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_69[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_70[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_71[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_72[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_73[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_74[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_75[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_76[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_77[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_78[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_79[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_80[2];

    /* vector of size 2 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float b_81[2];

} MPCC_solv_80N_no_warm_no_hard_invitedguest_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct MPCC_solv_80N_no_warm_no_hard_invitedguest_output
{
    /* vector of size 972 */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float X[972];

} MPCC_solv_80N_no_warm_no_hard_invitedguest_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct MPCC_solv_80N_no_warm_no_hard_invitedguest_info
{
    /* iteration number */
    solver_int32_default it;

	/* number of iterations needed to optimality (branch-and-bound) */
	solver_int32_default it2opt;
	
    /* inf-norm of equality constraint residuals */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float res_eq;
	
    /* inf-norm of inequality constraint residuals */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float res_ineq;

    /* primal objective */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float pobj;	
	
    /* dual objective */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float dobj;	

    /* duality gap := pobj - dobj */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float dgap;		
	
    /* relative duality gap := |dgap / pobj | */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float rdgap;		

	/* infinity norm of gradient of Lagrangian*/
	MPCC_solv_80N_no_warm_no_hard_invitedguest_float gradient_lag_norm;

    /* duality measure */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float mu;

	/* duality measure (after affine step) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float mu_aff;
	
    /* centering parameter */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float sigma;
	
    /* number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;
    
    /* number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;
    
    /* step size (affine direction) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float step_aff;
    
    /* step size (combined direction) */
    MPCC_solv_80N_no_warm_no_hard_invitedguest_float step_cc;    

	/* solvertime */
	MPCC_solv_80N_no_warm_no_hard_invitedguest_float solvetime;   

} MPCC_solv_80N_no_warm_no_hard_invitedguest_info;









/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Wednesday, March 23, 2022 9:06:46 AM */
/* User License expires on: (UTC) Saturday, April 23, 2022 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Saturday, April 23, 2022 10:00:00 PM (approx.) */
/* Solver Generation Request Id: 1e80b9b5-ce92-4bab-b122-34e25ac325e1 */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif
extern solver_int32_default MPCC_solv_80N_no_warm_no_hard_invitedguest_solve(MPCC_solv_80N_no_warm_no_hard_invitedguest_params *params, MPCC_solv_80N_no_warm_no_hard_invitedguest_output *output, MPCC_solv_80N_no_warm_no_hard_invitedguest_info *info, FILE *fs);

;



#ifdef __cplusplus
}
#endif

#endif
