/*
FORCESNLPsolver_fast : A fast customized optimization solver.

Copyright (C) 2013-2021 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v5.1.0 on Monday, March 21, 2022 at 8:07:00 AM */
#ifndef FORCESNLPsolver_fast_H
#define FORCESNLPsolver_fast_H

#ifndef SOLVER_STDIO_H
#define SOLVER_STDIO_H
#include <stdio.h>
#endif


#ifndef SOLVER_STANDARD_TYPES
#define SOLVER_STANDARD_TYPES

typedef signed char solver_int8_signed;
typedef unsigned char solver_int8_unsigned;
typedef char solver_int8_default;
typedef signed short int solver_int16_signed;
typedef unsigned short int solver_int16_unsigned;
typedef short int solver_int16_default;
typedef signed int solver_int32_signed;
typedef unsigned int solver_int32_unsigned;
typedef int solver_int32_default;
typedef signed long long int solver_int64_signed;
typedef unsigned long long int solver_int64_unsigned;
typedef long long int solver_int64_default;

#endif


/* DATA TYPE ------------------------------------------------------------*/
typedef double FORCESNLPsolver_fast_float;
typedef double FORCESNLPsolver_fast_ldl_s_float;
typedef double FORCESNLPsolver_fast_ldl_r_float;
typedef double FORCESNLPsolver_fast_callback_float;

typedef double FORCESNLPsolver_fastinterface_float;

/* SOLVER SETTINGS ------------------------------------------------------*/

/* MISRA-C compliance */
#ifndef MISRA_C_FORCESNLPsolver_fast
#define MISRA_C_FORCESNLPsolver_fast (0)
#endif

/* restrict code */
#ifndef RESTRICT_CODE_FORCESNLPsolver_fast
#define RESTRICT_CODE_FORCESNLPsolver_fast (0)
#endif

/* print level */
#ifndef SET_PRINTLEVEL_FORCESNLPsolver_fast
#define SET_PRINTLEVEL_FORCESNLPsolver_fast    (1)
#endif

/* timing */
#ifndef SET_TIMING_FORCESNLPsolver_fast
#define SET_TIMING_FORCESNLPsolver_fast    (1)
#endif

/* Numeric Warnings */
/* #define PRINTNUMERICALWARNINGS */

/* maximum number of iterations  */
#define SET_MAXIT_FORCESNLPsolver_fast			(200)	

/* scaling factor of line search (FTB rule) */
#define SET_FLS_SCALE_FORCESNLPsolver_fast		(FORCESNLPsolver_fast_float)(0.99)      

/* maximum number of supported elements in the filter */
#define MAX_FILTER_SIZE_FORCESNLPsolver_fast	(200) 

/* maximum number of supported elements in the filter */
#define MAX_SOC_IT_FORCESNLPsolver_fast			(4) 

/* desired relative duality gap */
#define SET_ACC_RDGAP_FORCESNLPsolver_fast		(FORCESNLPsolver_fast_float)(0.0001)

/* desired maximum residual on equality constraints */
#define SET_ACC_RESEQ_FORCESNLPsolver_fast		(FORCESNLPsolver_fast_float)(1E-06)

/* desired maximum residual on inequality constraints */
#define SET_ACC_RESINEQ_FORCESNLPsolver_fast	(FORCESNLPsolver_fast_float)(1E-06)

/* desired maximum violation of complementarity */
#define SET_ACC_KKTCOMPL_FORCESNLPsolver_fast	(FORCESNLPsolver_fast_float)(1E-06)


/* SOLVER RETURN CODES----------------------------------------------------------*/
/* solver has converged within desired accuracy */
#define OPTIMAL_FORCESNLPsolver_fast      (1)

/* maximum number of iterations has been reached */
#define MAXITREACHED_FORCESNLPsolver_fast (0)

/* solver has stopped due to a timeout */
#define TIMEOUT_FORCESNLPsolver_fast   (2)

/* wrong number of inequalities error */
#define INVALID_NUM_INEQ_ERROR_FORCESNLPsolver_fast  (-4)

/* factorization error */
#define FACTORIZATION_ERROR_FORCESNLPsolver_fast   (-5)

/* NaN encountered in function evaluations */
#define BADFUNCEVAL_FORCESNLPsolver_fast  (-6)

/* no progress in method possible */
#define NOPROGRESS_FORCESNLPsolver_fast   (-7)

/* regularization error */
#define REGULARIZATION_ERROR_FORCESNLPsolver_fast   (-9)

/* invalid values in parameters */
#define PARAM_VALUE_ERROR_FORCESNLPsolver_fast   (-11)

/* too small timeout given */
#define INVALID_TIMEOUT_FORCESNLPsolver_fast   (-12)

/* thread error */
#define THREAD_FAILURE_FORCESNLPsolver_fast  (-98)

/* locking mechanism error */
#define LOCK_FAILURE_FORCESNLPsolver_fast  (-99)

/* licensing error - solver not valid on this machine */
#define LICENSE_ERROR_FORCESNLPsolver_fast  (-100)

/* INTEGRATORS RETURN CODE ------------*/
/* Integrator ran successfully */
#define INTEGRATOR_SUCCESS (11)
/* Number of steps set by user exceeds maximum number of steps allowed */
#define INTEGRATOR_MAXSTEPS_EXCEEDED (12)





/* PARAMETERS -----------------------------------------------------------*/
/* fill this with data before calling the solver! */
typedef struct
{
    /* vector of size 8 */
    FORCESNLPsolver_fast_float xinit[8];

    /* vector of size 252 */
    FORCESNLPsolver_fast_float x0[252];

    /* vector of size 315 */
    FORCESNLPsolver_fast_float all_parameters[315];


} FORCESNLPsolver_fast_params;


/* OUTPUTS --------------------------------------------------------------*/
/* the desired variables are put here by the solver */
typedef struct
{
    /* vector of size 12 */
    FORCESNLPsolver_fast_float x01[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x02[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x03[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x04[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x05[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x06[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x07[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x08[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x09[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x10[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x11[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x12[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x13[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x14[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x15[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x16[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x17[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x18[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x19[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x20[12];

    /* vector of size 12 */
    FORCESNLPsolver_fast_float x21[12];


} FORCESNLPsolver_fast_output;


/* SOLVER INFO ----------------------------------------------------------*/
/* diagnostic data from last interior point step */
typedef struct
{
    /* iteration number */
    solver_int32_default it;

	/* number of iterations needed to optimality (branch-and-bound) */
	solver_int32_default it2opt;
	
    /* inf-norm of equality constraint residuals */
    FORCESNLPsolver_fast_float res_eq;
	
    /* inf-norm of inequality constraint residuals */
    FORCESNLPsolver_fast_float res_ineq;

	/* norm of stationarity condition */
    FORCESNLPsolver_fast_float rsnorm;

	/* max of all complementarity violations */
    FORCESNLPsolver_fast_float rcompnorm;

    /* primal objective */
    FORCESNLPsolver_fast_float pobj;	
	
    /* dual objective */
    FORCESNLPsolver_fast_float dobj;	

    /* duality gap := pobj - dobj */
    FORCESNLPsolver_fast_float dgap;		
	
    /* relative duality gap := |dgap / pobj | */
    FORCESNLPsolver_fast_float rdgap;		

    /* duality measure */
    FORCESNLPsolver_fast_float mu;

	/* duality measure (after affine step) */
    FORCESNLPsolver_fast_float mu_aff;
	
    /* centering parameter */
    FORCESNLPsolver_fast_float sigma;
	
    /* number of backtracking line search steps (affine direction) */
    solver_int32_default lsit_aff;
    
    /* number of backtracking line search steps (combined direction) */
    solver_int32_default lsit_cc;
    
    /* step size (affine direction) */
    FORCESNLPsolver_fast_float step_aff;
    
    /* step size (combined direction) */
    FORCESNLPsolver_fast_float step_cc;    

	/* solvertime */
	FORCESNLPsolver_fast_float solvetime;   

	/* time spent in function evaluations */
	FORCESNLPsolver_fast_float fevalstime;  


} FORCESNLPsolver_fast_info;









/* SOLVER FUNCTION DEFINITION -------------------------------------------*/
/* Time of Solver Generation: (UTC) Monday, March 21, 2022 8:07:02 AM */
/* User License expires on: (UTC) Saturday, April 23, 2022 10:00:00 PM (approx.) (at the time of code generation) */
/* Solver Static License expires on: (UTC) Saturday, April 23, 2022 10:00:00 PM (approx.) */
/* Solver Generation Request Id: ed9d58f2-5787-419a-8830-cd0e9a07430c */
/* examine exitflag before using the result! */
#ifdef __cplusplus
extern "C" {
#endif		

typedef void (*FORCESNLPsolver_fast_extfunc)(FORCESNLPsolver_fast_float* x, FORCESNLPsolver_fast_float* y, FORCESNLPsolver_fast_float* lambda, FORCESNLPsolver_fast_float* params, FORCESNLPsolver_fast_float* pobj, FORCESNLPsolver_fast_float* g, FORCESNLPsolver_fast_float* c, FORCESNLPsolver_fast_float* Jeq, FORCESNLPsolver_fast_float* h, FORCESNLPsolver_fast_float* Jineq, FORCESNLPsolver_fast_float* H, solver_int32_default stage, solver_int32_default iterations, solver_int32_default threadID);

extern solver_int32_default FORCESNLPsolver_fast_solve(FORCESNLPsolver_fast_params *params, FORCESNLPsolver_fast_output *output, FORCESNLPsolver_fast_info *info, FILE *fs, FORCESNLPsolver_fast_extfunc evalextfunctions_FORCESNLPsolver_fast);	













#ifdef __cplusplus
}
#endif

#endif
